### ISSUE TITLE
Add collection hooks.

### ISSUE THREAD

**Issue by almet** [Kinto/kinto.js#153] opened 2015-09-09 14:48 UTC
To be able to sign the collection before sending it to the kinto server, a hook mechanism would help.

For instance:

```js
var db = new Kinto(...);
var mycollection = db.collection('mycollection');
mycollection.on('sync-local-changes', callback);
```

I'm not sure about the name of the event, but that's the idea :)

**Comment by leplatrem** [comment] 2016-03-08 09:18
Duplicate of #154

**Closed by leplatrem** 2016-03-08 09:18 UTC
Labels: duplicate, ready
